version: '3'
services:
  # Database
  db:
    env_file:
      - ./envs/development/db.env
    container_name: imagen-${PRACTICE_NAME_VAR}-database-development
    image: mariadb:10.6
    volumes:
      - db_data:/var/lib/mariadb
    restart: always
    ports:
      - 8116:3306
    networks:
      - network
  # phpmyadmin
  phpmyadmin:
    env_file:
      - ./envs/development/db.env
    container_name: imagen-${PRACTICE_NAME_VAR}-apache-phpmyadmin
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8117:80'
    environment:
      PMA_HOST: imagen-${PRACTICE_NAME_VAR}-database-development
    networks:
      - network
  # Wordpress
  wordpress:
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file:
      - ./envs/development/.env
    container_name: imagen-${PRACTICE_NAME_VAR}-apache-development
    depends_on:
      - db
    ports:
      - '8111:80'
    restart: always
    volumes: 
      - ./wp-content:/var/www/html/wp-content
    environment:
      environment: development
    networks:
      - network
networks:
  network:
    name: 'imagen-${PRACTICE_NAME_VAR}-apache-network'
    external: true
volumes:
  db_data:
