version: '3'
services:
  # Database
  db:
    image: mariadb:10.6
    volumes:
      - db_data:/var/lib/mariadb
    restart: always
    ports:
      - 3116:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    container_name: wp_database
      
    networks:
      - wpsite
  # phpmyadmin
  phpmyadmin:
    container_name: phpmyadmin
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '3117:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password 
      UPLOAD_LIMIT: 1000M
    networks:
      - wpsite
  # Wordpress
  wordpress:
    container_name: wp_theme
    depends_on:
      - db
    image: imagen-practice-apache-wordpress
    ports:
      - '3111:80'
    restart: always
    volumes: 
      - wp_data:/var/www/html/wp-content
      - ./wp-content:/var/www/html/wp-content
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    networks:
      - wpsite
networks:
  wpsite:
volumes:
  db_data:
  wp_data: