FROM ubuntu:20.04

LABEL Chris Pashalis <cpashalis@imagendentalpartners.com>

# Install locales
RUN apt update && apt install -y locales
RUN locale-gen en_US.UTF-8

ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8
ENV DEBIAN_FRONTEND=noninteractive

# Get latest version of software-properties-common first
RUN apt update && apt upgrade -y && apt install -y software-properties-common

# Pre-add php repo
RUN add-apt-repository -y ppa:ondrej/php \
    && add-apt-repository universe \
    && apt update

# Basic Requirements
RUN apt update \
    && apt install -y apache2 apache2-utils apache2-bin apache2-data lsb-base mime-support perl procps curl unzip git gzip wget python3-pip sqlite3 memcached 

# PHP Requirements
RUN apt update \
    && apt install -y php8.1 php8.1-fpm php8.1-cli php8.1-mcrypt php8.1-gd php8.1-mysql \
    php8.1-imap php-memcached php8.1-mbstring php8.1-xml php8.1-curl \
    php8.1-sqlite3 php8.1-zip

# Wordpress Requirements
RUN apt update \
    && apt install -y libnuma-dev php8.1-intl php-pear php8.1-imagick \
    libpng-dev nasm autoconf automake libtool gettext pkg-config \
    php8.1-ps php8.1-pspell php8.1-tidy php8.1-xmlrpc php8.1-xsl

RUN update-alternatives --set php /usr/bin/php8.1

# Install Composer
RUN php -r "readfile('https://getcomposer.org/installer');" | php -- --install-dir=/usr/bin/ --filename=composer

# Install WP-CLI
RUN curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar \
    && chmod +x wp-cli.phar \
    && mv wp-cli.phar /usr/local/bin/wp

#Install text editor
RUN apt update && apt install -y vim

# Misc. Cleanup
RUN mkdir /run/php \
    && apt remove -y --purge software-properties-common \
    && apt -y autoremove \
    && apt clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* 

RUN curl -sL https://deb.nodesource.com/setup_16.x | bash -
RUN apt-get install -y nodejs
RUN npm install --global yarn

#COPY docker/uploads.ini /usr/local/etc/php/8.1/conf.d/uploads.ini

EXPOSE 80

COPY . /var/www/html

WORKDIR /var/www/html/wp-content/themes/imagen-practice-sage
RUN php /usr/bin/composer install --no-interaction && ls

RUN yarn && yarn build

#RUN mkdir -p /var/www/html/wp-content/plugins/all-in-one-wp-migration/storage
#RUN chown $(whoami):www-data -R /var/www/html/wp-content/plugins/all-in-one-wp-migration/storage && chmod -R 777 /var/www/html/web/app/plugins/all-in-one-wp-migration/storage

# RUN mkdir /var/www/html/web/app/uploads
RUN chown $(whoami):www-data -R /var/www/html/wp-content && chmod -R 755 /var/www/html/wp-content

WORKDIR /var/www/html/


